[0.259s] Traceback (most recent call last):
  File "/Users/hannahgillespie/miniconda3/envs/ros_env/lib/python3.11/site-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannahgillespie/miniconda3/envs/ros_env/lib/python3.11/site-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannahgillespie/miniconda3/envs/ros_env/lib/python3.11/site-packages/colcon_ros/task/ament_python/build.py", line 102, in build
    return await extension.build(additional_hooks=additional_hooks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannahgillespie/miniconda3/envs/ros_env/lib/python3.11/site-packages/colcon_core/task/python/build.py", line 94, in build
    available_commands = await self._get_available_commands(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hannahgillespie/miniconda3/envs/ros_env/lib/python3.11/site-packages/colcon_core/task/python/build.py", line 192, in _get_available_commands
    output = await check_output(
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/hannahgillespie/miniconda3/envs/ros_env/lib/python3.11/site-packages/colcon_core/subprocess.py", line 129, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/Users/hannahgillespie/miniconda3/envs/ros_env/bin/python3.11', '-W', 'ignore:setup.py install is deprecated', 'setup.py', '--help-commands'] to pass: /Users/hannahgillespie/miniconda3/envs/ros_env/bin/python3.11: can't open file '/Users/hannahgillespie/ros2_ws/src/drone_video_feed/setup.py': [Errno 2] No such file or directory

